src/apps/openfoodfacts/urls.py
from django.urls import path
from . import views

app_name = "openfoodfacts"

urlpatterns = [
    path(
        "products/<int:pk>/",
        views.ShowProductView.as_view(),
        name="products_list"
    ),
    path(
        "products/search/",
        views.SearchProductView.as_view(),
        name="products_search"
    ),
    path(
        "products/saved/",
        views.SavedProductsListView.as_view(),
        name="products_saved"
    ),
    path(
        "products/save/",
        views.SaveProductView.as_view(),
        name="products_save"
    )
]

src/urls.py
from django.contrib import admin
from django.urls import include, path


def trigger_error(request):
    return 1 / 0


urlpatterns = [
    path('', include('apps.core.urls'), name='core'),
    path('', include('apps.resources.urls'), name='resources'),
]


urlpatterns += [
    path('admin/', admin.site.urls, name='admin'),
    path('sentry-debug/', trigger_error),
    path('friendship/', include('friendship.urls')),
]

src/apps/openfoodfacts/templates/openfoodfacts/product_details.html
{% extends "layouts/base.html" %}

{% load static %}
{% block content %}
<section class="page-section bg-dark text-white" style="background-image: url('{{ product.img_url }}'); background-position: center center;">
    <div class="container text-center" >
        <h2 class="text-dark mb-4 bg-white">{{ product.product_name }}</h2>
        <div class="row">
            <div class="col-4">
                <img src="{% static 'images/nutriscore-grades/nutriscore-'|add:product.nutrition_grades|add:'.svg' %}" alt="nutriscore-{{ product.nutrition_grades }}" />
            </div>
            <p class="col-4 offset-4 mt-auto mb-auto text-dark bg-white">Repères nutritionnels pour 100g</p>
        </div>
        <div class="row">
            <div class="col-12 text-center">
                <a class="btn btn-primary" href="{{ product.url }}">Voir la fiche d'OpenFoodFacts</a>
            </div>
        </div>
    </div>
</section>
<h3 class="text-center my-5">Vous pouvez remplacer cet aliment par:</h3>
<section class="page-section p-0">
    <div class="container">
        <div class="row">
            {% csrf_token %}
                {% for sub in substitutes %}
                    <div class="col-md-4 mb-3">
                        <div class="thumbnail text-center">
                            <a href="{% url 'openfoodfacts:products_list' sub.pk %}">
                                <img
                                    {% if not sub.img_url%}
                                        src="{% static 'images/divers/no-product-image.png' %}"
                                    {% else %}
                                        src="{{ sub.img_url }}"
                                    {% endif %}
                                    alt="{{ sub.product_name }}"
                                    style="height:250px; max-width: 300px;"
                                />
                            </a>
                            <div class="caption text-center">
                                <p>{{ sub.product_name | truncatechars:25 }}</p>
                                {% if user.is_authenticated %}
                                    <form class="row" method="POST" action="{% url 'openfoodfacts:products_save' %}">
                                        <input type="hidden" name="product_id" value="{{ sub.pk }}" />
                                        <button class="btn btn-link col-6 offset-3" type="submit">
                                            <i class="fa fa-save text-primary" aria-hidden="true"></i>
                                            Sauvegarder
                                        </button>
                                    </form>
                                {% endif %}
                            </div>
                        </div>
                    </div>
            {% empty %}
                <p>Désolé nous n'avons pas de produits à proposer pour remplacer celui la.</p>
            {% endfor %}
        </div>
    </div>
</section>
{% endblock content %}