src/apps/core/urls.py
from django.urls import path
from . import views

app_name = "core"

urlpatterns = [
    path('', views.HomePageView.as_view(), name='home'),
    path(
        "legal_mentions/",
        views.LegalMentionsView.as_view(),
        name="legal_mentions"
    ),
    path("login/", views.LoginPageView.as_view(), name="login"),
    path("logout/", views.LogoutView.as_view(), name="logout"),
    path("signup/", views.SignUpView.as_view(), name="signup"),
    path("profil/", views.ProfilView.as_view(), name="profil"),
    path("friends/", views.FriendShip.as_view(), name="friendship"),
    path(
        "search_friend/",
        views.SearchFriend.as_view(),
        name="search_friend"
    ),
    path(
        "add_friend/",
        views.AddFriend.as_view(),
        name="add_friend"
    ),
    path(
        "friends/<int:id>/remove",
        views.RemoveFriendShip.as_view(),
        name="remove_friend"
    ),
    path(
        "friends/<int:id>/accept",
        views.AcceptFriendShip.as_view(),
        name="accept_friend"
    ),
    path(
        "friends/<int:id>/reject",
        views.RejectFriendShip.as_view(),
        name="reject_friend"
    ),
    path(
        "friends/<int:id>/cancel_friend_request",
        views.CancelFriendRequest.as_view(),
        name="cancel_friend_request"
    ),
    path(
        "friends/<int:id>/products_saved",
        views.FriendProductsSaved.as_view(),
        name="friend_products_saved"
    )
]

src/apps/resources/urls.py
from django.urls import path
from . import views

app_name = "resources"

urlpatterns = [
    path(
        "products/<int:pk>/",
        views.ShowProductView.as_view(),
        name="products_list"
    ),
    path(
        "products/search/",
        views.SearchProductView.as_view(),
        name="products_search"
    ),
    path(
        "products/saved/",
        views.SavedProductsListView.as_view(),
        name="products_saved"
    ),
    path(
        "products/save/",
        views.SaveProductView.as_view(),
        name="products_save"
    )
]

src/urls.py
from django.contrib import admin
from django.urls import include, path


def trigger_error(request):
    return 1 / 0


urlpatterns = [
    path('', include('apps.core.urls'), name='core'),
    path('', include('apps.resources.urls'), name='resources'),
]


urlpatterns += [
    path('admin/', admin.site.urls, name='admin'),
    path('sentry-debug/', trigger_error),
    path('friendship/', include('friendship.urls')),
]

src/apps/core/models.py
from django.db import models

# Create your models here.

src/apps/core/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import User


class LoginForm(forms.Form):
    email = forms.EmailField(
        help_text="Entrez une adresse email valide.",
        label="Adresse email",
        max_length=254,
        widget=forms.EmailInput(
            attrs={"class": "form-control"}
        )
    )
    password = forms.CharField(
        help_text="Entrez votre mot de passe.",
        label="Mot de passe",
        widget=forms.PasswordInput(
            attrs={"class": "form-control"}
        )
    )


class SignUpForm(UserCreationForm):
    username = forms.CharField(
        help_text="Entrez votre pseudo.",
        label="Pseudo",
        max_length=30,
        required=False,
        widget=forms.TextInput(
            attrs={"class": "form-control"}
        )
    )
    first_name = forms.CharField(
        help_text="Entrez votre prenom.",
        label="Prenom",
        max_length=30,
        required=False,
        widget=forms.TextInput(
            attrs={"class": "form-control"}
        )
    )
    last_name = forms.CharField(
        help_text="Entrez votre nom.",
        label="Nom",
        max_length=30,
        required=False,
        widget=forms.TextInput(
            attrs={"class": "form-control"}
        )
    )
    email = forms.EmailField(
        help_text="Entrez une adresse email valide.",
        label="Adresse email",
        max_length=254,
        widget=forms.EmailInput(
            attrs={"class": "form-control"}
        )
    )
    password1 = forms.CharField(
        help_text="Entrez votre mot de passe.",
        label="Mot de passe",
        widget=forms.PasswordInput(
            attrs={"class": "form-control"}
        )
    )
    password2 = forms.CharField(
        help_text="Entrez le même mot de passe que ci-dessus, pour vérification.",
        label="Verification de mot de passe.",
        widget=forms.PasswordInput(
            attrs={"class": "form-control"}
        )
    )

    class Meta:
        model = User
        fields = (
            "username", "first_name", "last_name", "email", "password1",
            "password2"
        )


class SearchUserForm(forms.Form):
    username = forms.CharField(
        label="Utilisateur",
        help_text="Rechercher un utilisateur",
        max_length=30,
        widget=forms.TextInput(
            attrs={"class": "form-control"}
        )
    )

src/apps/core/views.py
from friendship.models import Friend, FriendshipRequest

from django.conf import settings
from django.contrib.auth import authenticate, login, logout
from django.contrib.auth.models import User
from django.contrib.auth.mixins import LoginRequiredMixin
from django.shortcuts import (
    get_object_or_404,
    HttpResponseRedirect,
    render,
    redirect
)
from django.views.generic import TemplateView, View
from django.views.generic.edit import FormView
from django.urls import reverse

from apps.resources.models import BackupProduct, Product
from .forms import LoginForm, SignUpForm, SearchUserForm
from .utils import get_friendship


class HomePageView(TemplateView):
    """
    Home page view.
    """
    template_name = "core/index.html"


class LoginPageView(FormView):
    """
    Login page view.
    """
    form_class = LoginForm
    template_name = "core/login.html"

    def dispatch(self, request, *args, **kwargs):
        """
        Override dispatch method to redirect user if a user attempts to
        get the login page when the user is already logged.
        """
        if request.user.is_authenticated:
            return HttpResponseRedirect(reverse("core:home"))
        return super().dispatch(request, *args, **kwargs)

    def post(self, request, **kwargs):
        """
        Override post method to authenticate a user.
        """
        form = LoginForm(data=request.POST)
        if form.is_valid():
            # Retrieve email and password informations.
            email = form.cleaned_data.get('email')
            password = form.cleaned_data.get('password')
            # Get the user.
            try:
                user = User.objects.get(email=email)
            except User.DoesNotExist:
                error_msg = "L'adresse email renseignée n'est pas valide."
                form.add_error("email", error_msg)
                return render(request, self.template_name, {"form": form})
            # Try to connect with the user.
            is_correct_password = user.check_password(password)
            if user is not None and is_correct_password and user.is_active:
                user = authenticate(username=user.username, password=password)
                login(request, user)
                return HttpResponseRedirect(settings.LOGIN_REDIRECT_URL)
            elif not is_correct_password:
                form.add_error("password", "Mot de passe incorrect.")
            return render(request, self.template_name, {"form": form})

        return render(request, self.template_name, {"form": form})


class LogoutView(TemplateView):
    """
    Logout page view.
    """

    def get(self, request, **kwargs):
        """
        Override get method to logout the user.
        """
        logout(request)
        return redirect("core:home")


class ProfilView(LoginRequiredMixin, TemplateView):
    """
    Profil page view.
    """
    template_name = "core/profil.html"


class SignUpView(FormView):
    """
    Sign up page view.
    """
    form_class = SignUpForm
    template_name = "core/signup.html"

    def post(self, request, **kwargs):
        """
        Override post method to create a user.
        """
        form = SignUpForm(request.POST)
        if form.is_valid():
            user = form.save()
            user = authenticate(
                username=form.cleaned_data.get("username"),
                password=form.cleaned_data.get("password1")
            )
            login(request, user)
            return redirect("core:home")
        return render(request, self.template_name, {"form": form})


class LegalMentionsView(TemplateView):
    """
    Legal mentions page view.
    """
    template_name = "core/legal_mentions.html"


class FriendShip(LoginRequiredMixin, FormView):
    """
    Friendship page view.
    """
    form_class = SearchUserForm
    template_name = "core/friendship.html"

    def get(self, request, *args, **kwargs):
        """
        Get all the friendship requests.
        """
        kwargs.update(get_friendship(request.user))
        return self.render_to_response(self.get_context_data(**kwargs))


class AcceptFriendShip(LoginRequiredMixin, View):
    template_name = "core/friendship.html"

    def get(self, request, *args, **kwargs):
        """
        Override get method to accept a friend.
        """
        other_user = get_object_or_404(User, pk=kwargs["id"])
        friend_request = FriendshipRequest.objects.get(
            from_user=other_user, to_user=request.user
        )
        friend_request.accept()
        return HttpResponseRedirect(reverse("core:friendship"))


class RejectFriendShip(LoginRequiredMixin, View):
    def get(self, request, *args, **kwargs):
        """
        Override get method to reject a friend.
        """
        other_user = get_object_or_404(User, pk=kwargs["id"])
        friend_request = FriendshipRequest.objects.get(
            from_user=other_user, to_user=request.user
        )
        friend_request.delete()
        return HttpResponseRedirect(reverse("core:friendship"))


class RemoveFriendShip(LoginRequiredMixin, View):
    def get(self, request, *args, **kwargs):
        """
        Override get method to delete a friendship between two
        users.
        """
        other_user = get_object_or_404(User, pk=kwargs["id"])
        Friend.objects.remove_friend(self.request.user, other_user)
        return HttpResponseRedirect(reverse("core:friendship"))


class CancelFriendRequest(LoginRequiredMixin, View):
    def get(self, request, *args, **kwargs):
        """
        Override get method to cancel a friendship sent.
        """
        try:
            FriendshipRequest.objects.get(id=kwargs["id"]).delete()
        except FriendshipRequest.DoesNotExist:
            pass
        finally:
            return HttpResponseRedirect(reverse("core:friendship"))


class SearchFriend(LoginRequiredMixin, FormView):
    template_name = "core/friendship.html"
    form_class = SearchUserForm

    def post(self, request, **kwargs):
        """
        Override post method to search a user.
        """
        form = SearchUserForm(data=request.POST)
        kwargs.update(get_friendship(request.user))
        context = {
            "form": form,
            **kwargs
        }
        if form.is_valid():
            # Retrieve email and password informations.
            username = form.cleaned_data.get("username")
            friend_usernames = [f["username"] for f in context["friends"]]
            if (username != self.request.user.username and
                    username not in friend_usernames):
                # Get the user.
                try:
                    user = User.objects.get(username=username)
                    context["user_found"] = user
                except User.DoesNotExist:
                    error_msg = f"L'utilisateur {username} n'existe pas"
                    form.add_error("username", error_msg)
                    return render(request, self.template_name, context, status=404)
                return render(request, self.template_name, context)
        return render(request, self.template_name, context)


class AddFriend(LoginRequiredMixin, View):
    template_name = "core/friendship.html"

    def post(self, request, **kwargs):
        """
        Override post method to add a friend.
        """
        other_user = get_object_or_404(User, pk=request.POST["user_id"])
        Friend.objects.add_friend(
            request.user,
            other_user,
            message="Hey tu veux devenir mon ami ? :-)"
        )
        kwargs.update(get_friendship(request.user))
        context = {
            "form": SearchUserForm(),
            **kwargs
        }
        return render(request, self.template_name, context)


class FriendProductsSaved(LoginRequiredMixin, TemplateView):
    template_name = "core/profil.html"

    def get(self, request, **kwargs):
        """"
        Overriding GET method to show products saved by a friend.
        """
        other_user = get_object_or_404(User, pk=kwargs["id"])
        friendship = Friend.objects.filter(
            from_user=request.user, to_user=other_user
        )
        if not friendship:
            return render(request, "core/index.html", status=404)
        bp = BackupProduct.objects.filter(user=other_user)\
            .values_list("product_code", "category_name")
        products = [
            Product.objects.filter(code=b[0], category__name=b[1]).first()
            for b in bp
        ]
        context = {
            "friend": {
                "name": other_user.username,
                "email": other_user,
                "products": products
            }
        }
        request.user.username = other_user.username
        request.user.email = other_user.email
        return self.render_to_response(self.get_context_data(**context))

src/apps/core/templates/core/friendship.html
{% extends "layouts/base.html" %}

{% load static %}

{% block content %}
<div class="page-section bg-info">
    <div class="container">
        {% for field in form %}
            {% for error in field.errors %}
                <div class="alert alert-danger" role="alert">
                    <strong>{{ error|escape }}</strong>
                </div>
            {% endfor %}
        {% endfor %}
        <form action="{% url 'core:search_friend' %}" class=" mb-4 form-group" method="POST">
            {% csrf_token %}
            {% for field in form %}
                <div class="form-group">
                    <label for="{{ field.name }}">{{ field.label }}</label>
                    {{ field }}
                    <small class="form-text text-muted">{{ field.help_text }}</small>
                </div>
            {% endfor %}
        </form>
        {% if user_found %}
            <form class="form-inline" action="{% url 'core:add_friend' %}" method="POST">
                {% csrf_token %}
                <div class="form-group mb-2">
                    <input type="text" readonly class="form-control-plaintext" value="{{ user_found.username }}">
                </div>
                <div class="form-group mx-sm-3 mb-2">
                    <label class="sr-only" for="user_id">{{ user_found.username }}</label>
                    <input  type="hidden" name="user_id" value="{{ user_found.id }}">
                </div>
                <button type="submit" class="btn btn-primary mb-2">Ajouter en ami</button>
            </form>
        {% endif %}
        <p>Pending friend requests</p>
        <table class="table table-dark">
            <thead>
                <tr>
                    <th scope="col">#</th>
                    <th scope="col">Utilisateur</th>
                    <th scope="col">Message</th>
                    <th scope="col">Accepter / Refuser</th>
                </tr>
            </thead>
            <tbody>
                {% for obj in friendship %}
                    <tr>
                        <th scope="row">{{ forloop.counter }}</th>
                        <td>{{ obj.user.username }}</td>
                        <td>{{ obj.message | truncatechars:15 }}</td>
                        <td>
                            <a href="{% url 'core:accept_friend' obj.user.id %}" class="btn btn-success">O</a>
                            <a href="{% url 'core:reject_friend' obj.user.id %}" class="btn btn-danger">X</a>
                        </td>
                    </tr>
                {% endfor %}
            </tbody>
        </table>
        <p>Friends</p>
        <table class="table table-dark">
            <thead>
                <tr>
                    <th scope="col">#</th>
                    <th scope="col">Utilisateur</th>
                    <th scope="col">Supprimer</th>
                </tr>
            </thead>
            <tbody>
                {% for obj in friends %}
                    <tr>
                        <th scope="row">{{ forloop.counter }}</th>
                        <td><a href="{% url 'core:friend_products_saved' obj.id %}">{{ obj.username }}</a></td>
                        <td>
                            <a href="{% url 'core:remove_friend' obj.id %}" class="btn btn-danger">X</a>
                        </td>
                    </tr>
                {% endfor %}
            </tbody>
        </table>
        <p>Sent friend requests</p>
        <table class="table table-dark">
            <thead>
                <tr>
                    <th scope="col">#</th>
                    <th scope="col">Utilisateur</th>
                    <th scope="col">Annuler</th>
                </tr>
            </thead>
            <tbody>
                {% for obj in friendship_request_sent %}
                    <tr>
                        <th scope="row">{{ forloop.counter }}</th>
                        <td>{{ obj.username }}</td>
                        <td>
                            <a href="{% url 'core:cancel_friend_request' obj.id %}" class="btn btn-danger">X</a>
                        </td>
                    </tr>
                {% endfor %}
            </tbody>
        </table>
    </div>
</div>
{% endblock content %}

src/apps/core/templates/core/index.html
{% extends 'layouts/base.html' %}

{% load static %}
{% block content %}
    <!-- Masthead-->
    <header class="masthead h-100">
        {% if product_not_found %}
            <div class="position-absolute position-fixed alert alert-danger alert-dismissible fade show" style="left:30%; right:30%; z-index:99999; word-wrap:break-word;" role="alert">
                <strong>Holy guacamole!</strong> Aucun produit trouvé avec <br /><br />{{ product_not_found }}
                <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                <span aria-hidden="true">&times;</span>
                </button>
            </div>
        {% endif %}
        <div class="container h-100">
            <div class="row h-100 align-items-center justify-content-center text-center">
                <div class="col-12 align-self-end">
                    <h1 class="text-white-75 font-weight-light">Du gras, oui, mais de qualité !</h1>
                    <hr class="divider my-4" />
                </div>
                <div class="col-12 align-self-baseline">
                    <h2 class="text-white-75 font-weight-light mb-5">
                        Trouvez un produit de substitution pour ceux que vous consommez tous les jours.
                    </h2>
                    <hr class="divider my-4" />
                    <form class="form-inline justify-content-center" action="{% url 'resources:products_search' %}" method="GET">
                        {% csrf_token %}
                        <div class="form-group">
                            <input class="form-control" type="text" name="word" minlength="2" maxlength="100" placeholder="Nom du produit recherché">
                        </div>
                        <input class="btn btn-primary" type="submit" value="Chercher">
                    </form>
                </div>
            </div>
        </div>
    </header>
    <!-- Portfolio section-->
    <section id="portfolio">
        <div class="container-fluid p-0">
            <div class="my-4 text-center">
                <div class="col-12">
                    <h2>Colette et Remy</h2>
                </div>
            </div>
            <div class="my-4 text-center">
                <div class="col-12 row justify-content-center">
                    <h2 class="text-center col-lg-6 text-white-25 font-weight-light blockquote-footer">
                        Pur Beurre est l'initiative de deux amoureux de la gastronomie française,
                        Colette Tatou et Rémy, que vous avez déjà certainement rencontrés dans notre excellent restaurant Ratatouille.
                    </h2>
                </div>
            </div>
            <div class="row no-gutters">
                <div class="col-lg-6 col-sm-12 text-center">
                    <a class="portfolio-box" href="{% static 'images/colette/colette-tatou-full.png' %}">
                        <img class="img-fluid" src="{% static 'images/colette/colette-tatou-full.png' %}" alt="colette" />
                        <div class="portfolio-box-caption">
                            <div class="project-name">Colette</div>
                        </div>
                    </a>
                </div>
                <div class="col-lg-6 col-sm-12 text-center">
                    <a class="portfolio-box" href="{% static 'images/remy/remy.jpg' %}">
                        <img class="img-fluid" src="{% static 'images/remy/remy.jpg' %}" alt="remy" />
                        <div class="portfolio-box-caption">
                            <div class="project-name">Remy</div>
                        </div>
                    </a>
                </div>
            </div>
        </div>
    </section>
    <!-- Services section-->
    <section class="page-section bg-secondary" id="services">
        <div class="container">
            <h2 class="text-center mt-0">Contactez-nous !</h2>
            <div class="row justify-content-center">
                <h3 class="text-center col-lg-6 text-white font-weight-light blockquote-footer">
                    Face à la situation exceptionnelle, nous restons à vos côtés.
                    Toutes les mesures que nous mettons en œuvre pour continuer à répondre au mieux à vos attentes sont ici.
                </h3>
            </div>
            <hr class="divider my-4" />
            <div class="row">
                <div class="col-lg-6 col-sm-12 text-center">
                    <div class="mt-5">
                        <i class="fas fa-phone-alt fa-4x mb-4"></i>
                        <p class="text-light mb-0">+33 1 11 11 11 11</p>
                    </div>
                </div>
                <div class="col-lg-6 col-sm-12 text-center">
                    <div class="mt-5">
                        <i class="fas fa-4x fa-envelope mb-4"></i>
                        <p class="text-light mb-0"><a href="mailto:contact@purebeurre.com">contact@purebeurre.fr</a></p>
                    </div>
                </div>
            </div>
        </div>
    </section>
{% endblock content %}

src/apps/core/templates/core/login.html
{% extends "layouts/base.html" %}

{% load static %}
{% block content %}
    <div class="page-section bg-info">
        <div class="container">
            <div class="d-flex justify-content-center align-items-center container ">
                <div class="row  w-75">
                    {% for field in form %}
                        {% for error in field.errors %}
                            <div class="alert alert-danger" role="alert">
                                <strong>{{ error|escape }}</strong>
                            </div>
                        {% endfor %}
                    {% endfor %}
                    <form
                        action="{% url 'core:login' %}"
                        class="col-12 mb-4 border border-light rounded px-4 py-4"
                        method="POST"
                    >
                        {% csrf_token %}
                        {% for field in form %}
                            <div class="form-group">
                                <label for="{{ field.name }}">{{ field.label }}</label>
                                {{ field }}
                                <small class="form-text text-muted">{{ field.help_text }}</small>
                            </div>
                        {% endfor %}
                        <button type="submit" class="btn btn-primary">Se connecter</button>
                    </form>
                </div>
            </div>
        </div>
    </div>
{% endblock content %}

src/apps/core/templates/core/profil.html
{% extends "layouts/base.html" %}

{% load static %}
{% block content %}
<section class="page-section bg-dark text-white" style="background-image: url({% static 'images/remy/ratatouille-11.jpg' %}); background-position: center; background-size: cover; background-repeat: no-repeat;">
    <div class="container text-center" >
        {% if friend %}
        <div class="row">
            <p class="col-4 offset-4 mt-auto mb-auto text-dark bg-white">Vous regardez le profil de:</p>
        </div>
        {% endif %}
        <h2 class="text-dark mb-4 bg-white">{{ user.username }}</h2>
    </div>
</section>
<h3 class="text-center my-5">{{ user.email }}</h3>
<section class="page-section p-0 h-50">
    <div class="container">
        <div class="row">
            <div class="col-md-4 mb-3">
                <div class="thumbnail text-center">
                </div>
            </div>
        </div>
    </div>
    {% if friend %}
    <div class="container">
        <table class="table">
            <thead>
                <tr>
                <th scope="col">#</th>
                <th scope="col">Product</th>
                </tr>
            </thead>
            <tbody>
                {% for product in friend.products %}
                    <tr>
                        <th scope="row">{{ forloop.counter }}</th>
                        <td><a href="{% url 'resources:products_list' product.id %}">{{ product.product_name }}</a></td>
                    </tr>
                {% endfor %}
            </tbody>
        </table>
    </div>
    {% endif %}
</section>
{% endblock content %}

src/apps/core/templates/core/signup.html
{% extends "layouts/base.html" %}

{% block content %}
    <div class="page-section bg-info">
        <div class="container">
            <div class="d-flex justify-content-center align-items-center container ">
                <div class="row w-75">
                    <h1></h1>
                    <form action="{% url 'core:signup' %}" method="POST" class="col-12 mb-4">
                        {% csrf_token %}
                        {% for field in form %}
                            <div class="form-group">
                                {% for error in field.errors %}
                                    <div class="alert alert-danger" role="alert">
                                        <strong>{{ error|escape }}</strong>
                                    </div>
                                {% endfor %}
                                <label for="{{ field.name }}">{{ field.label }}</label>
                                {{ field }}
                                <small class="form-text text-muted">{{ field.help_text }}</small>
                            </div>
                        {% endfor %}
                        <button type="submit" class="btn btn-primary">S'inscrire</button>
                    </form>
                </div>
            </div>
        </div>
    </div>
{% endblock content %}