src/apps/core/urls.py
from django.urls import path
from . import views

app_name = "core"

urlpatterns = [
    path('', views.HomePageView.as_view(), name='home'),
    path(
        "legal_mentions/",
        views.LegalMentionsView.as_view(),
        name="legal_mentions"
    ),
    path("login/", views.LoginPageView.as_view(), name="login"),
    path("logout/", views.LogoutView.as_view(), name="logout"),
    path("signup/", views.SignUpView.as_view(), name="signup"),
    path("profil/", views.ProfilView.as_view(), name="profil"),
    path("friends/", views.FriendShip.as_view(), name="friendship"),
    path(
        "search_friend/",
        views.SearchFriend.as_view(),
        name="search_friend"
    ),
    path(
        "add_friend/",
        views.AddFriend.as_view(),
        name="add_friend"
    ),
    path(
        "friends/<int:id>/remove",
        views.RemoveFriendShip.as_view(),
        name="remove_friend"
    ),
    path(
        "friends/<int:id>/accept",
        views.AcceptFriendShip.as_view(),
        name="accept_friend"
    ),
    path(
        "friends/<int:id>/reject",
        views.RejectFriendShip.as_view(),
        name="reject_friend"
    ),
    path(
        "friends/<int:id>/cancel_friend_request",
        views.CancelFriendRequest.as_view(),
        name="cancel_friend_request"
    ),
    path(
        "friends/<int:id>/products_saved",
        views.FriendProductsSaved.as_view(),
        name="friend_products_saved"
    )
]

src/apps/resources/urls.py
from django.urls import path
from . import views

app_name = "resources"

urlpatterns = [
    path(
        "products/<int:pk>/",
        views.ShowProductView.as_view(),
        name="products_list"
    ),
    path(
        "products/search/",
        views.SearchProductView.as_view(),
        name="products_search"
    ),
    path(
        "products/saved/",
        views.SavedProductsListView.as_view(),
        name="products_saved"
    ),
    path(
        "products/save/",
        views.SaveProductView.as_view(),
        name="products_save"
    )
]

src/urls.py
from django.contrib import admin
from django.urls import include, path


def trigger_error(request):
    return 1 / 0


urlpatterns = [
    path('', include('apps.core.urls'), name='core'),
    path('', include('apps.resources.urls'), name='resources'),
]


urlpatterns += [
    path('admin/', admin.site.urls, name='admin'),
    path('sentry-debug/', trigger_error),
    path('friendship/', include('friendship.urls')),
]

src/templates/layouts/_footer.html
<!-- Footer -->
<footer class="page-footer pt-3 bg-light">
	<!-- Footer Elements -->
	<div class="container">
		<!-- Social buttons -->
		<ul class="list-unstyled list-inline text-center">
			<li class="list-inline-item">
				<a class="btn-floating btn-fb btn-lg text-dark" href="https://facebook.com">
					<i class="fab fa-facebook-f"> </i>
				</a>
			</li>
			<li class="list-inline-item">
				<a class="btn-floating btn-tw btn-lg text-dark" href="https://twitter.com">
					<i class="fab fa-twitter"> </i>
				</a>
			</li>
			<li class="list-inline-item">
				<a class="btn-floating btn-li btn-lg text-dark" href="https://fr.linkedin.com/">
					<i class="fab fa-linkedin-in"> </i>
				</a>
			</li>
		</ul>
		<!-- Social buttons -->
	</div>
	<!-- Footer Elements -->
	<div class="list-unstyled list-inline text-center">
		<small>
			<!-- Copyright -->
			<div class="footer-copyright py-3 list-inline-item">© 2020 Copyright:
				<a href="{% url 'core:home' %}">Pure beurre</a>
			</div>
			<!-- Copyright -->
			<ul class="list-unstyled list-inline list-inline-item">
				<li class="list-inline-item">
					<a class="text-muted" href="#">Conditions générales</a>
				</li>
				<li class="list-inline-item">
					<a class="text-muted" href="#">Charte de protection des données</a>
				</li>
				<li class="list-inline-item">
					<a class="text-muted" href="#">Politique relative aux cookies</a>
				</li>
				<li class="list-inline-item">
					<a class="text-muted" href="#">Paramètres des cookies</a>
				</li>
				<li class="list-inline-item">
					<a class="text-muted" href="{% url 'core:legal_mentions' %}">Mentions légales</a>
				</li>
			</ul>
		</small>
	</div>
		
	</footer>
	<!-- Footer -->

src/templates/layouts/_nav.html
{% load static %}
<!-- Navigation-->
<nav class="navbar navbar-expand-lg navbar-light fixed-top py-3" id="mainNav" {% if request.resolver_match.url_name == "products_list" %}style="background-color: gray;"{% endif %}>
    <div class="container">
        <a class="navbar-brand js-scroll-trigger" href="/">
            <img class="img-thumbnail" src="{% static 'logos/logo_pur_beurre.png' %}" alt="colette" />
            Pure beurre
        </a>
        <button class="navbar-toggler navbar-toggler-right" type="button" data-toggle="collapse" data-target="#navbarResponsive" aria-controls="navbarResponsive" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarResponsive">
            <ul class="navbar-nav ml-auto my-2 my-lg-0">
                {% if request.resolver_match.url_name != "login" and request.resolver_match.url_name != "signup" %}
                    <form class="form-inline" action="{% url 'resources:products_search' %}" method="GET">
                        {% csrf_token %}
                        <form class="form-inline" action="{% url 'resources:products_search' %}" method="GET">
                            {% csrf_token %}
                            <div class="form-group">
                                <input class="form-control" type="text" name="word" minlength="2" maxlength="100" placeholder="Nom du produit recherché">
                            </div>
                        </form>
                    </form>
                {% endif %}
                {% if user.is_authenticated %}
                    {% if user.is_superuser %}
                        <li class="nav-item"><a class="nav-link js-scroll-trigger" href="/admin"><i class="fa fa-user-shield fa-2x" aria-hidden="true"></i></a></li>
                    {% endif %}
                    <li class="nav-item"><a class="nav-link js-scroll-trigger" href="{% url 'core:friendship' %}"><i class="fas fa-users fa-2x"></i></a></li>
                    <li class="nav-item"><a class="nav-link js-scroll-trigger" href="{% url 'core:profil' %}"><i class="fas fa-user fa-2x"></i></a></li>
                    <li class="nav-item"><a class="nav-link js-scroll-trigger" href="{% url 'resources:products_saved' %}"><i class="fas fa-carrot fa-2x"></i></a></li>
                    <li class="nav-item"><a class="nav-link js-scroll-trigger" href="{% url 'core:logout' %}"><i class="fas fa-sign-out-alt fa-2x"></i></a></li>
                {% else %}
                    <li class="nav-item">
                        {% if request.resolver_match.url_name != "login" %}
                            <a class="nav-link js-scroll-trigger" href="{% url 'core:login' %}">Se connecter</a>
                        {% endif %}
                        {% if request.resolver_match.url_name != "signup" %}
                            <a class="nav-link js-scroll-trigger" href="{% url 'core:signup' %}">S'inscrire</a>
                        {% endif %}
                    </li>
                {% endif %}
            </ul>
        </div>
    </div>
</nav>

src/templates/layouts/base.html
<!DOCTYPE html>
<html lang="en">
    <head>
        <meta charset="utf-8" />
        <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no" />
        <meta name="description" content="Pure beurre app" />
        <meta name="author" content="RITCHY BLEZIN" />
        <title>Pure beurre</title>
        {% load static %}
        <link rel="shortcut icon" href="{% static 'logos/favicon.ico' %}" type="image/x-icon">
        <link rel="icon" href="{% static 'logos/favicon.ico' %}" type="image/x-icon">
        <!-- Font Awesome icons (free version)-->
        <script src="https://use.fontawesome.com/releases/v5.12.1/js/all.js" crossorigin="anonymous"></script>
        <!-- Google fonts-->
        <link href="https://fonts.googleapis.com/css?family=Merriweather+Sans:400,700" rel="stylesheet" />
        <link href="https://fonts.googleapis.com/css?family=Merriweather:400,300,300italic,400italic,700,700italic" rel="stylesheet" type="text/css" />
        <!-- Third party plugin CSS-->
        <link href="https://cdnjs.cloudflare.com/ajax/libs/magnific-popup.js/1.1.0/magnific-popup.min.css" rel="stylesheet" />
        <!-- Core theme CSS (includes Bootstrap)-->
        <link href="{% static 'css/styles.css' %}" rel="stylesheet" />
    </head>
    <body id="page-top">
        {% include 'layouts/_nav.html' %}
        {% block content %}{% endblock content %}
        {% include 'layouts/_footer.html' %}
        <!-- Bootstrap core JS-->
        <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.4.1/jquery.min.js"></script>
        <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/js/bootstrap.bundle.min.js"></script>
        <!-- Third party plugin JS-->
        <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery-easing/1.4.1/jquery.easing.min.js"></script>
        <script src="https://cdnjs.cloudflare.com/ajax/libs/magnific-popup.js/1.1.0/jquery.magnific-popup.min.js"></script>
        <!-- Core theme JS-->
        <script src="{% static 'js/scripts.js' %}"></script>
        {% block script %}{% endblock script %}
    </body>
</html>