src/apps/resources/urls.py
from django.urls import path
from . import views

app_name = "resources"

urlpatterns = [
    path(
        "products/<int:pk>/",
        views.ShowProductView.as_view(),
        name="products_list"
    ),
    path(
        "products/search/",
        views.SearchProductView.as_view(),
        name="products_search"
    ),
    path(
        "products/saved/",
        views.SavedProductsListView.as_view(),
        name="products_saved"
    ),
    path(
        "products/save/",
        views.SaveProductView.as_view(),
        name="products_save"
    )
]

src/urls.py
from django.contrib import admin
from django.urls import include, path


def trigger_error(request):
    return 1 / 0


urlpatterns = [
    path('', include('apps.core.urls'), name='core'),
    path('', include('apps.resources.urls'), name='resources'),
]


urlpatterns += [
    path('admin/', admin.site.urls, name='admin'),
    path('sentry-debug/', trigger_error),
    path('friendship/', include('friendship.urls')),
]

src/apps/resources/templates/resources/product_details.html
{% extends "layouts/base.html" %}

{% load static %}
{% block content %}
<section class="page-section bg-dark text-white" style="background-image: url('{{ product.img_url }}'); background-position: center center;">
    <div class="container text-center" >
        <div class="row bg-white mb-4 rounded">
            <div class="col-12">
                <h2 class="text-dark mb-4">{{ product.product_name }}</h2>
            </div>
            <div class="col-4">
                <img src="{% static 'images/nutriscore-grades/nutriscore-'|add:product.nutrition_grades|add:'.svg' %}" alt="nutriscore-{{ product.nutrition_grades }}" />
            </div>
            <p class="col-4 offset-4 mt-auto mb-auto text-dark">Repères nutritionnels pour 100g</p>
        </div>
        <div class="row">
            <div class="col-12 text-center">
                <a class="btn btn-primary" href="{{ product.url }}">Voir la fiche d'OpenFoodFacts</a>
            </div>
        </div>
    </div>
</section>
<h3 class="text-center my-5">Vous pouvez remplacer cet aliment par:</h3>
<section class="page-section p-0">
    <div class="container">
        <div class="row">
                {% for sub in substitutes %}
                    <div class="col-md-4 mb-3">
                        <div class="thumbnail text-center">
                            <a class="d-block border" href="{% url 'resources:products_list' sub.pk %}">
                                <img
                                    {% if not sub.img_url%}
                                        src="{% static 'images/divers/no-product-image.png' %}"
                                    {% else %}
                                        src="{{ sub.img_url }}"
                                    {% endif %}
                                    alt="{{ sub.product_name }}"
                                    style="height:250px; max-width: 300px;"
                                />
                            </a>
                            <div class="caption text-center">
                                <p>{{ sub.product_name | truncatechars:25 }}</p>
                                {% if user.is_authenticated %}
                                    <form class="row" method="POST" action="{% url 'resources:products_save' %}">
                                        {% csrf_token %}
                                        <input type="hidden" name="product_id" value="{{ sub.pk }}" />
                                        <button class="btn btn-link col-6 offset-3" type="submit">
                                            <i class="fa fa-save text-primary" aria-hidden="true"></i>
                                            Sauvegarder
                                        </button>
                                    </form>
                                {% endif %}
                                {% if sub.nutrition_grades == 'a' %}
                                    <p class="position-absolute sticky-top bg-success font-weight-bold border p-2 rounded-circle" style="right: 15px; border-width:3px !important;">{{ sub.nutrition_grades|upper }}</p>
                                {% elif sub.nutrition_grades == 'b' %}
                                    <p class="position-absolute sticky-top font-weight-bold border p-2 rounded-circle" style="right: 15px; border-width:3px !important; background-color: #85bb2f;">{{ sub.nutrition_grades|upper }}</p>
                                {% elif sub.nutrition_grades == 'c' %}
                                    <p class="position-absolute sticky-top bg-warning font-weight-bold border p-2 rounded-circle" style="right: 15px; border-width:3px !important;">{{ sub.nutrition_grades|upper }}</p>
                                {% elif sub.nutrition_grades == 'd' %}
                                    <p class="position-absolute sticky-top bg-primary font-weight-bold border p-2 rounded-circle" style="right: 15px; border-width:3px !important;">{{ sub.nutrition_grades|upper }}</p>
                                {% else %}
                                    <p class="position-absolute sticky-top bg-danger font-weight-bold border p-2 rounded-circle" style="right: 15px; border-width:3px !important;">{{ sub.nutrition_grades|upper }}</p>
                                {% endif %}
                            </div>
                        </div>
                    </div>
            {% empty %}
                <p>Désolé nous n'avons pas de produits à proposer pour remplacer celui la.</p>
            {% endfor %}
        </div>
    </div>
</section>
{% endblock content %}

src/apps/resources/templates/resources/products_saved.html
{% extends "layouts/base.html" %}

{% load static %}
{% block content %}
<section class="page-section bg-dark text-white">
    <div class="container">
        <div class="row text-center text-white mb-5">
            <div class="col-12 mx-auto">
                <h1 class="display-4">Mes aliments enregistrés</h1>
            </div>
        </div>
        <div class="row">
            <div class="col-lg-8 mx-auto">
                <!-- List group-->
                <ul class="list-group shadow">
                    <!-- list group item-->
                {% for obj in object_list %}
                    <li class="list-group-item">
                        <!-- Custom content-->
                        <div class="media align-items-lg-center flex-column flex-lg-row p-3">
                            <div class="media-body order-2 order-lg-1">
                                <h5 class="mt-0 font-weight-bold mb-2">{{ obj.product_name }}</h5>
                                <p class="font-italic text-muted mb-0 small">Code: {{ obj.code }}</p>
                                <p class="font-italic text-muted mb-0 small">Teneur en sel: {{ obj.salt }}</p>
                                <p class="font-italic text-muted mb-0 small">Teneur en graisse: {{ obj.fat }}</p>
                                <p class="font-italic text-muted mb-0 small">Teneur en sucre: {{ obj.sugars }}</p>
                                <p class="font-italic text-muted mb-0 small">Teneur en graisse saturée: {{ obj.saturated_fat }}</p>
                                <p class="font-italic text-muted mb-0 small">Où le trouver le produit: {{ obj.warehouse }}</p>
                                <p class="font-italic text-muted mb-0 small">Allergens: {{ obj.allergens }}</p>
                                <div class="d-flex align-items-center justify-content-between mt-1">
                                    {% if obj.id != "NID" %}
                                        <a href="{% url 'resources:products_list' obj.id %}" class="font-weight-bold my-2 text-dark">Voir la fiche produit</a>
                                    {% else %}
                                        <p class="text-dark m-0">Aucune fiche produit disponible</p>
                                    {% endif %}
                                    <img style="width: 150px" src="{% static 'images/nutriscore-grades/nutriscore-'|add:obj.nutrition_grades|add:'.svg' %}" alt="nutriscore-{{ obj.nutrition_grades }}" />
                                </div>
                            </div><img src="{{ obj.img_url }}" alt="{{ obj.product_name }}" width="140" height="170" class="ml-lg-5 order-1 order-lg-2">
                        </div> <!-- End -->
                    </li> <!-- End -->
                {% endfor %}
                </ul> <!-- End -->
            </div>
        </div>
    </div>
</section>
{% endblock content %}